# Generated by Django 6.0.1 on 2026-03-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('before', models.ImageField(upload_to='products/')),
                ('after', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blogs/'),
        ),
    ]
