# Generated by Django 6.0.1 on 2026-04-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_banda_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='after',
            field=models.ImageField(upload_to='banda/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='before',
            field=models.ImageField(upload_to='banda/'),
        ),
    ]
